name = "Ball & Chain"
group = "Flails"
restriction = "Chivalric"
quality = 12
heft = 14
length = 5
thrusting = false
aspect = "Blunt"
zone_die = 6
impact_die = 6
impact_mod = 5
weight = 4
price = 72
description = "(Horseman's flail) The chain both makes it harder for foes to defend and allows for more impactful strikes, as the wielder can better swing through a connecting blow. The spikes do not deliver an appreciable puncture injury but instead help the ball better grip an armoured target, similar in effect to a mace's flanges."
