name = "Bastard Sword"
group = "Swords"
restriction = "Chivalric"
quality = 12
heft = 14
length = 5
thrusting = false
aspect = "Edge"
zone_die = 6
impact_die = 10
impact_mod = 4
weight = 5
price = 184
description = "(Knight's sword · Hand-and-a-half sword) A large sword that enables strong combatants to wield it readily either one-handed (lng 6) or two-handed (lng 5)."
