name = "Battleaxe"
group = "Axes"
restriction = "Chivalric"
quality = 12
heft = 17
length = 5
thrusting = false
aspect = "Edge"
zone_die = 6
impact_die = 8
impact_mod = 7
weight = 6
price = 108
description = "(Long axe · Greataxe) Derived from the wood axe, the battleaxe concentrates its weight in the heavy blade, increasing impact but making it slower in handling. Wielding it one-handed increases reach (lng 6), but only the strongest may do so accurately."
