name = "Broadsword"
group = "Swords"
restriction = "Chivalric"
quality = 12
heft = 10
length = 5
thrusting = false
aspect = "Edge"
zone_die = 6
impact_die = 10
impact_mod = 3
weight = 3
price = 156
description = "(Arming sword • War sword) The most popular weapon of the feudal gentry, the broadsword allows for a high degree of control. This is a lethal advantage against all defences but mail and plate, which routinely turn its slicing blows."
