name = "Buckler"
group = "Shields"
restriction = "Common"
quality = 9
heft = 8
length = 1
thrusting = false
aspect = "Blunt"
zone_die = 6
impact_die = 6
impact_mod = 0
deflect = 1
weight = 3
price = 30
description = "A small, light shield wielded in the fist with the arm extended. A buckler is carried when larger shields would be too cumbersome or militant-looking."
