name = "Club"
group = "Clubs"
restriction = "Common"
quality = 9
heft = 11
length = 4
thrusting = false
aspect = "Blunt"
zone_die = 6
impact_die = 6
impact_mod = 1
weight = 3
price = 12
description = "(Cudgel · Truncheon) Improvised clubs such as a table leg or branch have wq8; an unwieldy crowbar does d6 + 3b (wq 11 • hft 13 • lng 4 • zd d6 • 4 lb • 9d). Larger crafted clubs increase impact to d6 + 2b (wq 9 • hft 14 • lng 5 • zd d6 • 5 lb • 18d)."
