name = "Dagger"
group = "Knives"
restriction = "Simple"
quality = 11
heft = 7
length = 3
thrusting = true
aspect = "Point"
zone_die = 6
impact_die = 8
impact_mod = 2
weight = 1
price = 24
description = "A combat knife used primarily for thrusting, but also having one or both edges sharpened (lng 3 • d10 + 1e). Not well balanced for throwing."
