name = "Grainflail"
group = "Flails"
restriction = "Common"
quality = 9
heft = 11
length = 5
thrusting = false
aspect = "Blunt"
zone_die = 6
impact_die = 6
impact_mod = 2
weight = 3
price = 16
description = "An agriculture tool used for threshing, the grainflail offers the same advantages to attacks as other similarly designed flail weapons."
