name = "Handaxe"
group = "Axes"
restriction = "Simple"
quality = 11
heft = 13
length = 5
thrusting = false
aspect = "Edge"
zone_die = 6
impact_die = 8
impact_mod = 5
weight = 4
price = 84
description = "(Bearded axe) A combat axe designed for one-handed use. The hooked portion of the blade in the 'bearded' style pictured is used to pull opposing shields aside or to help disarm foes (treat as an Unarmed [Grab] attack using the axe's Length 5)."
