name = "Javelin"
group = "Polearms"
restriction = "Simple"
quality = 10
heft = 11
length = 5
thrusting = true
aspect = "Point"
zone_die = 6
impact_die = 8
impact_mod = 4
weight = 3
price = 36
description = "(Light spear • Dart) A small one-handed throwing spear. The head is either barbed (as listed) or narrowed, similar to a bodkin arrow (d8 + 3p • ar 2p)."
