name = "Knife"
group = "Knives"
restriction = "Common"
quality = 10
heft = 6
length = 2
thrusting = true
aspect = "Point"
zone_die = 6
impact_die = 8
impact_mod = 1
weight = 1
price = 6
description = "(Hunting knife) A utilitarian blade, also with a sharp edge (lng 2 • d10 + 0e)."
