name = "Lance"
group = "Polearms"
restriction = "Chivalric"
quality = 11
heft = 17
length = 8
thrusting = true
aspect = "Point"
zone_die = 8
impact_die = 8
impact_mod = 6
weight = 7
price = 120
description = "(Long spear) A spear used primarily from horseback, where the rider makes downward overhead strikes or couches it underarm to charge."
