name = "Máng"
group = "Swords"
restriction = "Simple"
quality = 10
heft = 11
length = 5
thrusting = false
aspect = "Edge"
zone_die = 6
impact_die = 8
impact_mod = 4
weight = 3
price = 108
description = "(Bladed club • Orcish falchion) A crude and unwieldy weapon made by the Gargun, the Mang is designed for hewing strikes like those of an axe."
