name = "Mankar"
group = "Swords"
restriction = "Simple"
quality = 11
heft = 9
length = 3
thrusting = false
aspect = "Edge"
zone_die = 6
impact_die = 8
impact_mod = 3
weight = 2
price = 84
description = "(Short falchion • Orcish scimitar) Lighter and shorter than the Mang, the Mankar allows for effective chopping strikes despite its clumsiness."
