name = "Maul"
group = "Clubs"
restriction = "Simple"
quality = 12
heft = 18
length = 5
thrusting = false
aspect = "Blunt"
zone_die = 6
impact_die = 6
impact_mod = 6
weight = 7
price = 96
description = "(Sledgehammer) The metal-headed maul given here is a weapon of war. The wood-headed version is a common tool (wq 10 • hft 17 • d6 + 5b • 9 lb • 24d)."
