name = "Morningstar"
group = "Clubs"
restriction = "Simple"
quality = 11
heft = 15
length = 5
thrusting = false
aspect = "Point"
zone_die = 6
impact_die = 8
impact_mod = 4
weight = 5
price = 48
description = "The heavy, usually two-handed club features short spikes that help better defeat armour and inflict lethal penetrating wounds."
