name = "Pickaxe"
group = "Axes"
restriction = "Common"
quality = 9
heft = 18
length = 5
thrusting = false
aspect = "Point"
zone_die = 6
impact_die = 8
impact_mod = 5
weight = 5
price = 18
description = "(Mattock) A tool with a spiked head to break up rock and hard soil; its opposite flat head is for prying. While unwieldy as a weapon, a pickaxe punctures heavy armour by concentrating its swung momentum into a narrow point."
