name = "Pitchfork"
group = "Polearms"
restriction = "Common"
quality = 9
heft = 12
length = 5
thrusting = true
aspect = "Point"
zone_die = 6
impact_die = 8
impact_mod = 3
weight = 4
price = 9
description = "The ubiquitous forked agricultural tool."
