name = "Poleaxe"
group = "Polearms"
restriction = "Chivalric"
quality = 11
heft = 18
length = 6
thrusting = false
aspect = "Edge"
zone_die = 6
impact_die = 8
impact_mod = 7
weight = 7
price = 96
description = "A weapon similar in length to the spear, but with three primary modes: an axe head used for chopping strikes (top row); opposite this, a hammer head for bludgeoning (middle row); and, extending from the end of the shaft, a top spike for thrusting (bottom row). There can be a spike from the other, bottom end, too."
