name = "Roundshield"
group = "Shields"
restriction = "Simple"
quality = 10
heft = 10
length = 1
thrusting = false
aspect = "Blunt"
zone_die = 6
impact_die = 6
impact_mod = 1
deflect = 3
weight = 6
price = 48
description = "A medium shield that, along with a sturdy helm, is the core element of defence."
