name = "Shôrkána"
group = "Axes"
restriction = "Simple"
quality = 10
heft = 10
length = 5
thrusting = false
aspect = "Edge"
zone_die = 6
impact_die = 8
impact_mod = 4
weight = 2
price = 48
description = "(Throwing axe) Originating in Shorkyne, this light throwing axe has a distinctive arching head."
