name = "Shortsword"
group = "Swords"
restriction = "Simple"
quality = 12
heft = 8
length = 4
thrusting = false
aspect = "Edge"
zone_die = 6
impact_die = 10
impact_mod = 2
weight = 2
price = 96
description = "(Sword) Carried by many common folk, the shortsword primarily calls for cutting strikes. Its shorter length turns to an advantage in tight quarters against foes wielding spears and longer swords."
