name = "Tower Shield"
group = "Shields"
restriction = "Simple"
quality = 11
heft = 12
length = 1
thrusting = false
aspect = "Blunt"
zone_die = 8
impact_die = 6
impact_mod = 1
deflect = 5
weight = 8
price = 96
description = "A heavy rectangular shield that provides greater protection to the legs; usually wielded in large foot formations."
