name = "Trident"
group = "Polearms"
restriction = "Simple"
quality = 12
heft = 14
length = 6
thrusting = true
aspect = "Point"
zone_die = 8
impact_die = 8
impact_mod = 5
weight = 6
price = 72
description = "A rare weapon whose strange three-pronged head makes it a popular spectacle in arena games. Its heft, otherwise, makes it a little less practical than the spear for mass warfare."
