name = "Warflail"
group = "Flails"
restriction = "Simple"
quality = 11
heft = 17
length = 6
thrusting = false
aspect = "Blunt"
zone_die = 6
impact_die = 6
impact_mod = 6
weight = 5
price = 60
description = "A military version of the grainflail, the warflail incorporates a metal chain attachment and studs, the latter for improving the chances for landing solid blows, as the flanges do for a mace."
