name = "Warhammer"
group = "Axes"
restriction = "Chivalric"
quality = 11
heft = 13
length = 5
thrusting = false
aspect = "Blunt"
zone_die = 6
impact_die = 6
impact_mod = 4
weight = 4
price = 84
description = "A heavy-headed bludgeoning weapon designed to dent and smash rigid armours. Its opposing spike can be used to make point strikes (d8 + 3p • ar 2p)."
