name = "Wood Axe"
group = "Axes"
restriction = "Common"
quality = 9
heft = 16
length = 5
thrusting = false
aspect = "Edge"
zone_die = 6
impact_die = 8
impact_mod = 6
weight = 5
price = 12
description = "(Felling axe · Broad axe) A heavy, two-handed tool used for felling trees and chopping wood."
