[Armor]
name = "Tunic, sleeved"
material = "Cloth"
covers = [
    "Shoulder",
    "UpperArm",
    "Elbow",
    "Forearm",
    "Thorax",
    "Abdomen",
    "Pelvis",
]
description = "A full-sleeved tunic providing coverage from shoulder to wrist and down to the thighs, favored in colder climates."
