[Weapon]
name = "Dagger"
description = "A combat knife used primarily for thrusting, but also having one or both edges sharpened (lng 3 • d10 + 1e). Not well balanced for throwing."

[[Weapon.modes]]

[Weapon.modes.Melee]
length = 3
heft = 7
thrust = true
two_hand = false
aspect = "Point"
zone_die = 6
impact_die = 8
impact_mod = 2
defense_mod = 0
