[Weapon]
name = "Máng"
description = "(Bladed club • Orcish falchion) A crude and unwieldy weapon made by the Gargun, the Mang is designed for hewing strikes like those of an axe."

[[Weapon.modes]]

[Weapon.modes.Melee]
length = 5
heft = 11
thrust = false
two_hand = false
aspect = "Edge"
zone_die = 6
impact_die = 8
impact_mod = 4
defense_mod = -10
