[Weapon]
name = "Pitchfork"
description = "The ubiquitous forked agricultural tool."

[[Weapon.modes]]

[Weapon.modes.Melee]
length = 5
heft = 12
thrust = true
two_hand = false
aspect = "Point"
zone_die = 6
impact_die = 8
impact_mod = 3
defense_mod = 0
