[Weapon]
name = "Shôrkána"
description = "(Throwing axe) Originating in Shorkyne, this light throwing axe has a distinctive arching head."

[[Weapon.modes]]

[Weapon.modes.Melee]
length = 5
heft = 10
thrust = false
two_hand = false
aspect = "Edge"
zone_die = 6
impact_die = 8
impact_mod = 4
defense_mod = -5
