[Weapon]
name = "Shortsword"
description = "(Sword) Carried by many common folk, the shortsword primarily calls for cutting strikes. Its shorter length turns to an advantage in tight quarters against foes wielding spears and longer swords."

[[Weapon.modes]]

[Weapon.modes.Melee]
length = 4
heft = 8
thrust = false
two_hand = false
aspect = "Edge"
zone_die = 6
impact_die = 10
impact_mod = 2
defense_mod = 0

[[Weapon.modes]]

[Weapon.modes.Melee]
length = 4
heft = 8
thrust = true
two_hand = false
aspect = "Point"
zone_die = 6
impact_die = 8
impact_mod = 1
defense_mod = 0
