name = "60lb Composite Bow"
group = "Bows"
restriction = "Simple"
quality = 11
draw = 60
base_range = 180
impact_mod = 2
weight = 2
price = 78
description = "(Ketari bow) An expensive and time-consuming glued construction of strips of wood with animal sinew on the 'back', or outer side (for flexing), and animal bone on its 'belly', or inner side (for resisting); can be wielded as a fragile club (lng 4 • zd d6 • d6 + 0b • WQ reduced by 5 in Weapon Damage Rolls)."
