name = "300lb Composite Crossbow"
group = "Crossbows"
restriction = "Simple"
quality = 12
draw = 300
base_range = 300
impact_mod = 6
weight = 9
price = 204
description = "(Siege crossbow) With a string as thick as a thumb and a composite wood and horn prod, the stout compound crossbow almost invariably requires a mechanical spanner. For this reason many are relegated to siege defence, where the shooters can more easily gain shelter during the time-consuming reloading."
