name = "100lb Longbow"
group = "Bows"
restriction = "Simple"
quality = 10
draw = 100
base_range = 210
impact_mod = 3
weight = 3
price = 54
description = "(Self bow) A bow made of a single-piece wooden stave; can be used as a fragile club (lng 5 • zd d8 • d6 + 0b • WQ reduced by five in Weapon Damage Rolls)."
