name = "150lb Longbow"
group = "Bows"
restriction = "Simple"
quality = 11
draw = 150
base_range = 270
impact_mod = 5
weight = 4
price = 72
description = "(Self bow) A bow made of a single-piece wooden stave; can be used as a fragile club (lng 5 • zd d8 • d6 + 0b • WQ reduced by five in Weapon Damage Rolls)."
