name = "80lb Wooden Crossbow"
group = "Crossbows"
restriction = "Common"
quality = 10
draw = 80
base_range = 180
impact_mod = 1
weight = 3
price = 60
description = "(Hunting crossbow) Light-draw versions are not uncommon hunting weapons. The archer's ability to hold and aim shots grants an advantage in stalking game."
