name = "¾-Helm"
material = "Kurbul"
covers = [
    "Skull",
    "Face",
]
description = "A kurbul helmet extending to protect the face as well as the skull, with eye slits or an open-face guard allowing reasonable visibility."
