name = "Tunic, sleeved"
material = "Quilted"
covers = [
    "Shoulder",
    "UpperArm",
    "Elbow",
    "Forearm",
    "Thorax",
    "Abdomen",
    "Pelvis",
]
description = "A full-sleeved quilted tunic offering comprehensive coverage, its layered and stitched construction superior to simple padding."
