name = "Coat"
material = "Quilted"
covers = [
    "Shoulder",
    "UpperArm",
    "Elbow",
    "Forearm",
    "Thorax",
    "Abdomen",
    "Pelvis",
    "Thigh",
]
description = "A long quilted garment with full sleeves, the extensive stitching throughout creating a rigid yet flexible protective layer."
